name: pr

on:
  push:
    branches:
      - "pull-request/[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-builder:
    needs:
      - changed-files
      - checks
      - conda-cpp-build
      - conda-cpp-tests
      - conda-cpp-checks
      - conda-notebook-tests
      - conda-python-build
      - conda-python-tests
      - docs-build
      - wheel-build-pylibcugraph
      - wheel-tests-pylibcugraph
      - wheel-build-cugraph
      - wheel-tests-cugraph
      - wheel-build-nx-cugraph
      - wheel-tests-nx-cugraph
      - wheel-build-cugraph-dgl
      - wheel-tests-cugraph-dgl
      - wheel-build-cugraph-pyg
      - wheel-tests-cugraph-pyg
      - wheel-build-cugraph-equivariant
      - wheel-tests-cugraph-equivariant
      - devcontainer
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/pr-builder.yaml@branch-24.10
    if: always()
    with:
      needs: ${{ toJSON(needs) }}
  changed-files:
    runs-on: ubuntu-latest
    name: "Check changed files"
    outputs:
      test_cpp: ${{ steps.changed-files.outputs.cpp_any_changed == 'true' }}
      test_notebooks: ${{ steps.changed-files.outputs.notebooks_any_changed == 'true' }}
      test_python: ${{ steps.changed-files.outputs.python_any_changed == 'true' }}
    steps:
      - name: Get PR info
        id: get-pr-info
        uses: rapidsai/shared-actions/get-pr-info@main
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          fetch-depth: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).commits }}
          persist-credentials: false
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          base_sha: ${{ fromJSON(steps.get-pr-info.outputs.pr-info).base.sha }}
          files_yaml: |
            cpp:
              - '**'
              - '!docs/**'
              - '!img/**'
              - '!notebooks/**'
              - '!python/**'
              # TODO: Remove this before merging
              - '!.github/**'
            notebooks:
              - '**'
              - '!docs/**'
              # TODO: Remove this before merging
              - '!.github/**'
            python:
              - '**'
              - '!docs/**'
              - '!img/**'
              - '!notebooks/**'
              # TODO: Remove this before merging
              - '!.github/**'
  checks:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/checks.yaml@branch-24.10
    with:
      enable_check_generated_files: false
  conda-cpp-build:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-build.yaml@branch-24.10
    with:
      build_type: pull-request
      node_type: cpu32
  conda-cpp-tests:
    needs: [conda-cpp-build, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-tests.yaml@branch-24.10
    if: needs.changed-files.outputs.test_cpp == 'true'
    with:
      build_type: pull-request
  conda-cpp-checks:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-cpp-post-build-checks.yaml@branch-24.10
    with:
      build_type: pull-request
      enable_check_symbols: true
      symbol_exclusions: (cugraph::ops|hornet|void writeEdgeCountsKernel|void markUniqueOffsetsKernel)
  conda-python-build:
    needs: conda-cpp-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-build.yaml@branch-24.10
    with:
      build_type: pull-request
  conda-python-tests:
    needs: [conda-python-build, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/conda-python-tests.yaml@branch-24.10
    if: needs.changed-files.outputs.test_python == 'true'
    with:
      build_type: pull-request
  conda-notebook-tests:
    needs: [conda-python-build, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-24.10
    if: needs.changed-files.outputs.test_notebooks == 'true'
    with:
      build_type: pull-request
      node_type: "gpu-v100-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:cuda11.8.0-ubuntu22.04-py3.10"
      run_script: "ci/test_notebooks.sh"
  docs-build:
    needs: conda-python-build
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/custom-job.yaml@branch-24.10
    with:
      build_type: pull-request
      node_type: "gpu-v100-latest-1"
      arch: "amd64"
      container_image: "rapidsai/ci-conda:cuda11.8.0-ubuntu22.04-py3.10"
      run_script: "ci/build_docs.sh"
  wheel-build-pylibcugraph:
    needs: checks
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.10
    with:
      build_type: pull-request
      script: ci/build_wheel_pylibcugraph.sh
      extra-repo: rapidsai/cugraph-ops
      extra-repo-sha: branch-24.10
      extra-repo-deploy-key: CUGRAPH_OPS_SSH_PRIVATE_DEPLOY_KEY
      node_type: cpu32
  wheel-tests-pylibcugraph:
    needs: [wheel-build-pylibcugraph, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.10
    if: needs.changed-files.outputs.test_python == 'true'
    with:
      build_type: pull-request
      script: ci/test_wheel_pylibcugraph.sh
  wheel-build-cugraph:
    needs: wheel-tests-pylibcugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.10
    with:
      build_type: pull-request
      script: ci/build_wheel_cugraph.sh
      extra-repo: rapidsai/cugraph-ops
      extra-repo-sha: branch-24.10
      extra-repo-deploy-key: CUGRAPH_OPS_SSH_PRIVATE_DEPLOY_KEY
  wheel-tests-cugraph:
    needs: [wheel-build-cugraph, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.10
    if: needs.changed-files.outputs.test_python == 'true'
    with:
      build_type: pull-request
      script: ci/test_wheel_cugraph.sh
  wheel-build-nx-cugraph:
    needs: wheel-tests-pylibcugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.10
    with:
      build_type: pull-request
      script: ci/build_wheel_nx-cugraph.sh
  wheel-tests-nx-cugraph:
    needs: [wheel-build-nx-cugraph, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.10
    if: needs.changed-files.outputs.test_python == 'true'
    with:
      build_type: pull-request
      script: ci/test_wheel_nx-cugraph.sh
  wheel-build-cugraph-dgl:
    needs: wheel-tests-cugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.10
    with:
      build_type: pull-request
      script: ci/build_wheel_cugraph-dgl.sh
  wheel-tests-cugraph-dgl:
    needs: [wheel-build-cugraph-dgl, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.10
    if: needs.changed-files.outputs.test_python == 'true'
    with:
      build_type: pull-request
      script: ci/test_wheel_cugraph-dgl.sh
      matrix_filter: map(select(.ARCH == "amd64"))
  wheel-build-cugraph-pyg:
    needs: wheel-tests-cugraph
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.10
    with:
      build_type: pull-request
      script: ci/build_wheel_cugraph-pyg.sh
  wheel-tests-cugraph-pyg:
    needs: [wheel-build-cugraph-pyg, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.10
    if: needs.changed-files.outputs.test_python == 'true'
    with:
      build_type: pull-request
      script: ci/test_wheel_cugraph-pyg.sh
      matrix_filter: map(select(.ARCH == "amd64"))
  wheel-build-cugraph-equivariant:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-build.yaml@branch-24.10
    with:
      build_type: pull-request
      script: ci/build_wheel_cugraph-equivariant.sh
  wheel-tests-cugraph-equivariant:
    needs: [wheel-build-cugraph-equivariant, changed-files]
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/wheels-test.yaml@branch-24.10
    if: needs.changed-files.outputs.test_python == 'true'
    with:
      build_type: pull-request
      script: ci/test_wheel_cugraph-equivariant.sh
      matrix_filter: map(select(.ARCH == "amd64"))
  devcontainer:
    secrets: inherit
    uses: rapidsai/shared-workflows/.github/workflows/build-in-devcontainer.yaml@branch-24.10
    with:
      arch: '["amd64"]'
      cuda: '["12.5"]'
      node_type: cpu32
      extra-repo-deploy-key: CUGRAPH_OPS_SSH_PRIVATE_DEPLOY_KEY
      build_command: |
        sccache -z;
        build-all --verbose -j$(nproc --ignore=1) -DBUILD_CUGRAPH_MG_TESTS=ON;
        sccache -s;
